2 i
khrvr/algorithms pull request #11
Opened 2021-12-10 08:56 UTC by khrvr

2021-12-12 18:05 UTC, DmitryKorepanov requested changes

2021-12-12 18:05 UTC, DmitryKorepanov commented on 132006498.cpp
> +			part_arr.push_back(arr[i]);
quicksort не должен тратить память на сортировку, все перестановки должны быть в исходном массиве

2021-12-12 18:06 UTC, DmitryKorepanov commented
Нужна ссылка на успешную посылку в контест

2021-12-12 18:20 UTC, khrvr commented
> Нужна ссылка на успешную посылку в контест

Для экономии места я в ее честь назвал файл

2021-12-14 21:27 UTC, DmitryKorepanov approved these changes

2021-12-14 21:28 UTC, DmitryKorepanov commented
Имя файла эт здорово, но ссылка всё равно нужна

2021-12-14 21:42 UTC, merged